name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools pkg-config libx11-dev libxkbcommon-dev libwayland-dev libxkbcommon-x11-dev
      
      - name: Check
        run: cargo check --target x86_64-unknown-linux-musl

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: x86_64-unknown-linux-musl
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools pkg-config libx11-dev libxkbcommon-dev libwayland-dev libxkbcommon-x11-dev
      
      - name: Run clippy
        run: cargo clippy --target x86_64-unknown-linux-musl -- -D warnings
